config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :loans
  resources :buyers
  resources :users
  
  root   'sessions#new'
  get    'login',         to: 'sessions#new'
  post   'login',         to: 'sessions#create'
  get    'logout',        to: 'sessions#destroy'
  
  get    'home',          to: 'users#home'
  get    'add_loan',      to: 'loans#new'
  get    'view_loan',     to: 'loans#view'
  get    'view_payment',  to: 'payments#view'
  
  get    'reports/view/',  to: 'reports#view'
  get    'view_reports/',  to: 'reports#view'
  get    'print_report',   to: 'reports#print_report'
  
  get    'buyer_search',   to: 'buyers#search'
  get    'add_payment',    to: 'buyers#add_payment'
  get    'loan_search',    to: 'buyers#search_loans'
  
  get    'amortization_calculator', to: 'users#amortization_calculator'
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password

	validates_confirmation_of :password

	validates_uniqueness_of :username
	validates_presence_of :username

	validates_length_of :password, :in => 6..20, :on => :create
	validates_presence_of :password_confirmation, if: :password_changed?
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def home
  
  end
  
  def amortization_calculator
    @months = params[:months].to_i
    @interest_rate = (params[:interest_rate].to_i/100.0) / 12
    @loan_amount = params[:loan_amount].to_i
    
    @interest_amount = Array.new
    @principal_amount = Array.new
    @balance_due = Array.new
    
    @monthly = compute_monthly(@loan_amount, @interest_rate, @months).round(2)
    @previous_balance = @loan_amount

    for i in 1..@months
      @interest_amount << (@previous_balance * @interest_rate).round(2)
      @principal_amount << (((@interest_rate * (1 + @interest_rate) ** @months) / ((1 + @interest_rate) ** @months - 1) * @loan_amount) - (@interest_amount.last)).round(2)
      @balance_due << (@previous_balance - @principal_amount.last).round(2)
      @previous_balance = (@previous_balance - @principal_amount.last).round(2)
    end
  end
  
  def compute_monthly(purchase_price, interest_rate, numberOfMonths)
    # get the 80% of principal amount
    forInstallment = purchase_price
    
    # calculate monthly payment
    monthly = forInstallment * (interest_rate * (1 + interest_rate) ** numberOfMonths) / ((1 + interest_rate) ** numberOfMonths - 1)
    
    return monthly
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/users/amortization_calculator.html.haml
= form_tag amortization_calculator_path, :method => 'get' do
  .form-inline
    .form-group
      = number_field_tag :months, params[:months], :class => 'form-control'
    .form-group
      = number_field_tag :interest_rate, params[:interest_rate], :class => 'form-control'
    .form-group
      = number_field_tag :loan_amount, params[:loan_amount], :class => 'form-control'
    .form-group
      = submit_tag 'Compute', :name => nil, :class => 'btn btn-default'
%hr

%table.table.table-striped
  %thead
    %tr
      %th Payment Number
      %th Payment Amount
      %th Interest Amount
      %th Principal Reduction
      %th Balance Due

  %tbody
    - for i in 0..@interest_amount.count-1
      %tr
        %td= i+1
        %td= @monthly
        %td= @interest_amount.at(i)
        %td= @principal_amount.at(i)
        %td= @balance_due.at(i)

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/home.html.haml
%h1 Amortization Calculator

= form_tag amortization_calculator_path, :method => 'get' do
  .form-inline
    .form-group
      = number_field_tag :months, params[:months], :class => 'form-control', :placeholder => "Number of Months"
    .form-group
      = number_field_tag :interest_rate, params[:interest_rate], :class => 'form-control', :placeholder => "Interest Rate"
    .form-group
      = number_field_tag :loan_amount, params[:loan_amount], :class => 'form-control', :placeholder => "Loan Amount"
    .form-group
      = submit_tag 'Compute', :name => nil, :class => 'btn btn-default'
%hr

%table.table.table-striped
  %thead
    %tr
      %th Payment Number
      %th Payment Amount
      %th Interest Amount
      %th Principal Reduction
      %th Balance Due

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Username
      %th Password
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Password:
  = @user.password

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path