config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :loans
  resources :buyers
  resources :users
  
  root   'sessions#new'
  get    'login',         to: 'sessions#new'
  post   'login',         to: 'sessions#create'
  get    'logout',        to: 'sessions#destroy'
  
  get    'home',          to: 'users#home'
  get    'add_loan',      to: 'loans#new'
  get    'view_loan',     to: 'loans#view'
  get    'view_payment',  to: 'payments#view'
  
  get    'reports/view/',  to: 'reports#view'
  get    'view_reports/',  to: 'reports#view'
  get    'print_report',   to: 'reports#print_report'
  
  get    'buyer_search',   to: 'buyers#search'
  get    'add_payment',    to: 'buyers#add_payment'
  get    'loan_search',    to: 'buyers#search_loans'
  
  get    'amortization_calculator', to: 'users#amortization_calculator'
end

app/models/loan.rb
class Loan < ActiveRecord::Base
    belongs_to :buyer, dependent: :delete
    has_many :payment, dependent: :destroy
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
    @buyer_id = params[:loan][:buyer_id]
  end

  # GET /loans/1/edit
  def edit
  end
  
  def view
    @buyer_id = params[:loan][:buyer_id]
    @loans = Loan.where('buyer_id' => @buyer_id)
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)
    @loan.monthly_installment = compute_monthly(@loan).round(2)
    @loan.downpayment = (@loan.purchase_price * 0.2).round(2)
    @loan.balance_penalty_amount = 0

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def compute_monthly(loan)
    # get the 80% of principal amount
    forInstallment = loan.purchase_price * 0.8
    
    # get the number of years based on the interest rate
    if loan.interest_rate == 15
      terms = 5
    elsif loan.interest_rate == 17
      terms = 7
    elsif loan.interest_rate == 18
      terms = 10
    end
    
   
    
    
    # calculate number of months
    numberOfMonths = terms * 12
    
    # get the monthly interest rate
    interest_rate = (loan.interest_rate/100.0) / 12.0
    
    # calculate monthly payment
    monthly = forInstallment * (interest_rate * (1 + interest_rate) ** numberOfMonths) / ((1 +  interest_rate) ** numberOfMonths - 1)
  
    return monthly
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    @loan.monthly_installment = compute_monthly(@loan)
    
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:TCT, :subdivision_name, :block, :lot, :lot_area, :floor_area, :loan_type, :purchase_price, :monthly_installment, :interest_rate, :buyer_id)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.haml
= form_for @loan do |f|
  - if @loan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@loan.errors.count, "error")} prohibited this loan from being saved:"
      %ul
        - @loan.errors.full_messages.each do |msg|
          %li= msg
  %table
    %tr
      %td TCT
      %td
        .form-inline
          .form-group
            = f.number_field :TCT, :class => "form-control"
    %tr
      %td Subdivision Name
      %td
        .form-inline
          .form-group
            = f.text_field :subdivision_name, :class => "form-control"
    %tr
      %td Loan Type
      %td
        .form-inline
          .form-group
            = f.radio_button :loan_type, "lot_only"
            Lot Only
            = f.radio_button :loan_type, "house_and_lot"
            House and Lot
            = f.radio_button :loan_type, "duplex_house"
            Duplex House
    %tr
      %td Block
      %td
        .form-inline
          .form-group
            = f.number_field :block, :class => "form-control"
    %tr
      %td Lot
      %td
        .form-inline
          .form-group
            = f.number_field :lot, :class => "form-control"
    %tr
      %td Lot Area
      %td
        .form-inline
          .form-group
            = f.number_field :lot_area, :class => "form-control"
    %tr
      %td Floor Area
      %td
        .form-inline
          .form-group
            = f.number_field :floor_area, :class => "form-control"
    %tr
      %td Purchase Price
      %td
        .form-inline
          .form-group
            = f.text_field :purchase_price, :class => "form-control"
    %tr
      %td Interest Rate
      %td
        .form-inline
          .form-group
            = f.radio_button :interest_rate, 15
            15%, 5 years to pay
            = f.radio_button :interest_rate, 17
            17%, 7 years to pay
            = f.radio_button :interest_rate, 18
            18%, 10 years to pay
  .field
    = f.hidden_field :buyer_id, :value => @buyer_id
  .actions
    = f.submit 'Save', :class => "btn btn-success"

app/views/loans/edit.html.haml
%h1 Editing loan

= render 'form'

= link_to 'Show', @loan
\|
= link_to 'Back', view_loan_path(:loan => {:buyer_id => @loan.buyer_id})

app/views/loans/index.html.haml
%h1 Listing loans

%table.table.table-striped
  %thead
    %tr
      %th TCT
      %th Subdivision name
      %th Block
      %th Lot
      %th Lot area
      %th Floor area
      %th Purchase price
      %th Downpayment Amount
      %th Monthly installment
      %th Interest rate
      %th Fully Paid?
      %th
      %th
      %th

  %tbody
    - @loans.each do |loan|
      %tr
        %td= loan.TCT
        %td= loan.subdivision_name
        %td= loan.block
        %td= loan.lot
        %td= loan.lot_area
        %td= loan.floor_area
        %td= loan.purchase_price
        %td= loan.purchase_price * 0.2
        %td= loan.monthly_installment
        %td= loan.interest_rate
        %td= loan.is_fully_paid
        %td= link_to 'View Payments', view_payment_path("payment" => { :loan_id => loan.id })
        - if !loan.is_fully_paid
          %td= link_to 'Add Payment', new_payment_path("payment" => { :loan_id => loan.id })
        - else
          %td
        %td= link_to 'Edit', edit_loan_path(loan)
        %td= link_to 'Destroy', loan, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/loans/new.html.haml
%h1 New loan

= render 'form', :buyer_id => @buyer_id

= link_to 'Back', loans_path

app/views/loans/show.html.haml
%p#notice= notice

%p
  %b Tct:
  = @loan.TCT
%p
  %b Subdivision name:
  = @loan.subdivision_name
%p
  %b Block:
  = @loan.block
%p
  %b Lot:
  = @loan.lot
%p
  %b Lot area:
  = @loan.lot_area
%p
  %b Floor area:
  = @loan.floor_area
%p
  %b Purchase price:
  = @loan.purchase_price
%p
  %b Monthly installment:
  = @loan.monthly_installment
%p
  %b Interest rate:
  = @loan.interest_rate

= link_to 'Edit', edit_loan_path(@loan)
\|
= link_to 'Back', view_loan_path(:loan => {:buyer_id => @loan.buyer_id})

app/views/loans/view.html.haml
%h1 Listing loans

%table.table.table-striped
  %thead
    %tr
      %th TCT
      %th Subdivision name
      %th Block
      %th Lot
      %th Lot area
      %th Floor area
      %th Purchase price
      %th Downpayment Amount
      %th Monthly installment
      %th Interest rate
      %th Fully Paid?
      %th
      %th
      %th
      %th
      %th

  %tbody
    - @loans.each do |loan|
      %tr
        %td= loan.TCT
        %td= loan.subdivision_name
        %td= loan.block
        %td= loan.lot
        %td= loan.lot_area
        %td= loan.floor_area
        %td= loan.purchase_price
        %td= loan.downpayment
        %td= loan.monthly_installment
        %td= loan.interest_rate
        %td= loan.is_fully_paid
        %td= link_to 'View Payments', view_payment_path("payment" => { :loan_id => loan.id }), :class => 'btn btn-info'
        - if !loan.is_fully_paid
          %td= link_to 'Add Payment', new_payment_path("payment" => { :loan_id => loan.id }), :class => 'btn btn-success'
        - else
          %td
        %td= link_to 'Edit', edit_loan_path(loan), :class => 'btn btn-primary'
        %td= link_to 'Destroy', loan, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'