config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :loans
  resources :buyers
  resources :users
  
  root   'sessions#new'
  get    'login',         to: 'sessions#new'
  post   'login',         to: 'sessions#create'
  get    'logout',        to: 'sessions#destroy'
  
  get    'home',          to: 'users#home'
  get    'add_loan',      to: 'loans#new'
  get    'view_loan',     to: 'loans#view'
  get    'view_payment',  to: 'payments#view'
  
  get    'reports/view/',  to: 'reports#view'
  get    'view_reports/',  to: 'reports#view'
  get    'print_report',   to: 'reports#print_report'
  
  get    'buyer_search',   to: 'buyers#search'
  get    'add_payment',    to: 'buyers#add_payment'
  get    'loan_search',    to: 'buyers#search_loans'
  
  get    'amortization_calculator', to: 'users#amortization_calculator'
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
    has_many :loan, dependent: :destroy
    
    def self.search(search)
     if search
       where(['CONCAT(first_name, " ",  family_name) LIKE ?', "%#{search}%"])
     else
      scoped
     end
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/add_payment.html.haml
= form_tag loan_search_path, :method => 'get' do
  .form-inline
    .form-group
      = text_field_tag :search, params[:search], :class => 'form-control'
    .form-group
      = submit_tag 'Search', :name => nil, :class => 'btn btn-default'

app/views/buyers/edit.html.haml
%h1 Editing buyer

= render 'form'
%hr
= link_to 'Show', @buyer, :class => 'btn btn-info'
&nbsp;
= link_to 'Back', buyers_path, :class => 'btn btn-default'

app/views/buyers/index.html.haml
%h1 Listing buyers

= form_tag buyer_search_path, :method => 'get' do
  .form-inline
    .form-group
      = text_field_tag :search, params[:search], :class => 'form-control'
    .form-group
      = submit_tag 'Search', :name => nil, :class => 'btn btn-default'
%hr

%table.table.table-striped
  %thead
    %tr
      %th First Name
      %th Family Name
      %th
      %th
      %th

  %tbody
    - @buyers.each do |buyer|
      %tr
        %td= buyer.first_name
        %td= buyer.family_name
        %td= link_to 'Show', buyer, :class => 'btn btn-info'
        %td= link_to 'Edit', edit_buyer_path(buyer), :class => 'btn btn-primary'
        %td= link_to 'Destroy', buyer, :method => :delete, :class => 'btn btn-danger', :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Buyer', new_buyer_path, :class => 'btn btn-success'

app/views/buyers/new.html.haml
%h1 New buyer

= render 'form'

= link_to 'Back', buyers_path

app/views/buyers/search.html.haml
%h1 Listing buyers

= form_tag buyer_search_path, :method => 'get' do
  .form-inline
    .form-group
      = text_field_tag :search, params[:search], :class => 'form-control'
    .form-group
      = submit_tag 'Search', :name => nil, :class => 'btn btn-default'
%hr

%table.table.table-striped
  %thead
    %tr
      %th First Name
      %th Family Name
      %th
      %th
      %th

  %tbody
    - @buyers.each do |buyer|
      %tr
        %td= buyer.first_name
        %td= buyer.family_name
        %td= link_to 'Show', buyer, :class => 'btn btn-info'
        %td= link_to 'Edit', edit_buyer_path(buyer), :class => 'btn btn-primary'
        %td= link_to 'Destroy', buyer, :method => :delete, :class => 'btn btn-danger', :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Buyer', new_buyer_path, :class => 'btn btn-success'

app/views/buyers/search_loans.html.haml
%h1 Listing loans

= form_tag loan_search_path, :method => 'get' do
  .form-inline
    .form-group
      = text_field_tag :search, params[:search], :class => 'form-control'
    .form-group
      = submit_tag 'Search', :name => nil, :class => 'btn btn-default'

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Tct
      %th Subdivision name
      %th Block
      %th Lot
      %th Lot area
      %th Floor area
      %th Purchase price
      %th Downpayment Amount
      %th Monthly installment
      %th Interest rate
      %th Fully Paid?
      %th
      %th
      %th
      %th

  %tbody
    - @buyers.each do |buyer|
      - buyer.loan.each do |loan|
        %tr
          %td= loan.buyer.first_name + ' ' + loan.buyer.family_name
          %td= loan.TCT
          %td= loan.subdivision_name
          %td= loan.block
          %td= loan.lot
          %td= loan.lot_area
          %td= loan.floor_area
          %td= loan.purchase_price
          %td= loan.purchase_price * 0.2
          %td= loan.monthly_installment
          %td= loan.interest_rate
          %td= loan.is_fully_paid
          %td= link_to 'View Payments', view_payment_path("payment" => { :loan_id => loan.id }), :class => 'btn btn-info'
          - if !loan.is_fully_paid
            %td= link_to 'Add Payment', new_payment_path("payment" => { :loan_id => loan.id }), :class => 'btn btn-success'
          - else
            %td
          %td= link_to 'Edit', edit_loan_path(loan), :class => 'btn btn-primary'
          %td= link_to 'Destroy', loan, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'
          

app/views/buyers/show.html.haml
%p#notice= notice

%h2 Personal Reference
%table.table.table-striped
  %tr
    %td First Name
    %td= @buyer.first_name
  %tr
    %td Middle Name
    %td= @buyer.middle_name
  %tr
    %td Last Name
    %td= @buyer.family_name
  %tr
    %td Birthdate
    %td= @buyer.birthdate
  %tr
    %td Citizenship
    %td= @buyer.citizenship
  %tr
    %td Sex
    %td= @buyer.sex
  %tr
    %td Civil Status
    %td= @buyer.civil_status
  %tr
    %td No. of Dependents
    %td= @buyer.no_of_dependents
  %tr
    %td Home Address
    %td= @buyer.home_address
  %tr
    %td Zip Code
    %td= @buyer.home_zip_code
  %tr
    %td No. Of Years Stay
    %td= @buyer.years_of_stay
  %tr
    %td Home Telephone No.
    %td= @buyer.home_tel_number
  %tr
    %td Foreign / Provincial Home Address
    %td= @buyer.prov_address
  %tr
    %td ACR / Resident Card No.
    %td= @buyer.acr_resident_card_number
  %tr
    %td Zip Code
    %td= @buyer.prov_zip_code
  %tr
    %td Education
    %td= @buyer.education
  %tr
    %td Cellphone No.
    %td= @buyer.cellphone_number
  %tr
    %td E-mail Address
    %td= @buyer.email_address
  %tr
    %td SSS / HDMF / GSIS No.
    %td= @buyer.sss_hdmf_gsis_number
  %tr
    %td TIN
    %td= @buyer.tin
  %tr
    %td Occupation
    %td= @buyer.occupation
  %tr
    %td Employment Type
    %td= @buyer.employment_type
  %tr
    %td Total Years Working / In Business
    %td= @buyer.years_worked
  %tr
    %td Total Years Abroad
    %td= @buyer.years_abroad
  %tr
    %td Date Current Contract Ends
    %td= @buyer.contract_end
  
%h2 Employment History
%table.table.table-bordered
  %tr 
    %td Period Covered
    %td Position
    %td Employment Status
    %td Employer / Business Name
    %td Nature of Business
    %td Office Tel. No.
  %tr 
    %td= @buyer.period_covered1
    %td= @buyer.position1
    %td= @buyer.employment_status1
    %td= @buyer.employer1
    %td= @buyer.nature1
    %td= @buyer.office_tel_no1
  %tr
    %td= @buyer.period_covered2
    %td= @buyer.position2
    %td= @buyer.employment_status2
    %td= @buyer.employer2
    %td= @buyer.nature2
    %td= @buyer.office_tel_no2
  %tr
    %td= @buyer.period_covered3
    %td= @buyer.position3
    %td= @buyer.employment_status3
    %td= @buyer.employer3
    %td= @buyer.nature3
    %td= @buyer.office_tel_no3
  
%table.table.table-striped
  %tr
    %td Life Insurance
    %td= @buyer.insurance
  %tr
    %td Coverage / Amount
    %td= @buyer.coverage_amount
    
%h2 Spouse
%table.table.table-striped
  %tr
    %td First Name
    %td= @buyer.spouse_first_name
  %tr
    %td Middle Name
    %td= @buyer.spouse_middle_name
  %tr
    %td Last Name
    %td= @buyer.spouse_family_name
  %tr
    %td Birthdate
    %td= @buyer.spouse_birthdate
  %tr
    %td Citizenship
    %td= @buyer.spouse_citizenship
  %tr
    %td Sex
    %td= @buyer.spouse_sex
  %tr
    %td Civil Status
    %td= @buyer.spouse_civil_status
  %tr
    %td No. of Dependents
    %td= @buyer.spouse_no_of_dependents
  %tr
    %td Home Address
    %td= @buyer.spouse_home_address
  %tr
    %td Zip Code
    %td= @buyer.spouse_home_zip_code
  %tr
    %td Education
    %td= @buyer.spouse_education
  %tr
    %td Cellphone No.
    %td= @buyer.spouse_cellphone_number
  %tr
    %td E-mail Address
    %td= @buyer.spouse_email_address
  %tr
    %td SSS / HDMF / GSIS No.
    %td= @buyer.spouse_sss_hdmf_gsis_number
  %tr
    %td Occupation
    %td= @buyer.spouse_occupation
  %tr
    %td Employment Type
    %td= @buyer.spouse_employment_type
  %tr
    %td Total Years Working / In Business
    %td= @buyer.spouse_years_worked
  %tr
    %td Total Years Abroad
    %td= @buyer.spouse_years_abroad
  %tr
    %td Date Current Contract Ends
    %td= @buyer.spouse_contract_end
    
%h2 Employment History
%table.table.table-bordered
  %tr 
    %td Period Covered
    %td Position
    %td Employment Status
    %td Employer / Business Name
    %td Nature of Business
    %td Office Tel. No.
  %tr 
    %td= @buyer.spouse_period_covered1
    %td= @buyer.spouse_position1
    %td= @buyer.spouse_employment_status1
    %td= @buyer.spouse_employer1
    %td= @buyer.spouse_nature1
    %td= @buyer.spouse_office_tel_no1
  %tr
    %td= @buyer.spouse_period_covered2
    %td= @buyer.spouse_position2
    %td= @buyer.spouse_employment_status2
    %td= @buyer.spouse_employer2
    %td= @buyer.spouse_nature2
    %td= @buyer.spouse_office_tel_no2
  %tr
    %td= @buyer.spouse_period_covered3
    %td= @buyer.spouse_position3
    %td= @buyer.spouse_employment_status3
    %td= @buyer.spouse_employer3
    %td= @buyer.spouse_nature3
    %td= @buyer.spouse_office_tel_no3
  
%table.table.table-striped
  %tr
    %td Life Insurance
    %td= @buyer.spouse_insurance
  %tr
    %td Coverage / Amount
    %td= @buyer.spouse_coverage_amount
  
  
= link_to 'Edit', edit_buyer_path(@buyer), :class => 'btn btn-primary'
&nbsp;
= link_to 'Add Loan', add_loan_path("loan" => { :buyer_id => @buyer.id }), :class => 'btn btn-success'
&nbsp;
= link_to 'View Loans', view_loan_path("loan" => { :buyer_id => @buyer.id }), :class => 'btn btn-info'
&nbsp;
= link_to 'Back', buyers_path, :class => 'btn btn-default'