config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :loans
  resources :buyers
  resources :users
  
  root   'sessions#new'
  get    'login',         to: 'sessions#new'
  post   'login',         to: 'sessions#create'
  get    'logout',        to: 'sessions#destroy'
  
  get    'home',          to: 'users#home'
  get    'add_loan',      to: 'loans#new'
  get    'view_loan',     to: 'loans#view'
  get    'view_payment',  to: 'payments#view'
  
  get    'reports/view/',  to: 'reports#view'
  get    'view_reports/',  to: 'reports#view'
  get    'print_report',   to: 'reports#print_report'
  
  get    'buyer_search',   to: 'buyers#search'
  get    'add_payment',    to: 'buyers#add_payment'
  get    'loan_search',    to: 'buyers#search_loans'
  
  get    'amortization_calculator', to: 'users#amortization_calculator'
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  - if session['user_id'] != nil
    %ul.nav.navbar-nav
      %li
        = link_to 'Home', home_path
      %li
        = link_to 'Buyers', buyers_path
      %li
        = link_to 'Add Payment', add_payment_path
      %li
        = link_to 'Reports', view_reports_path
      %li
        = link_to 'Logout', logout_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Housing Installment System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<div class="container">
  <%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
    <!-- <%= debug(params) if Rails.env.development? %> -->
</div>

</body>
</html>